"""Firmware management: list ports, compile, flash via arduino-cli."""
from __future__ import annotations

import asyncio
import json
import logging
import os
import re
import shlex
import time
from pathlib import Path
from typing import AsyncIterator

from .config import ROOT_DIR, settings

log = logging.getLogger("meobot.firmware")

FQBN = "esp8266:esp8266:nodemcuv2"
SKETCH_DIR = ROOT_DIR / "firmware" / "KatBot"
BUILD_DIR = ROOT_DIR / "firmware" / "build"
RELEASES_DIR = ROOT_DIR / "firmware" / "releases"

_CLI = os.path.join(os.environ.get("LOCALAPPDATA", ""), "Arduino15", "arduino-cli.exe")

# Shared state
_status: dict = {"phase": "idle", "ok": None, "message": "", "ts": 0}
_flash_lock = asyncio.Lock()

_VER_RE = re.compile(r"^\d+\.\d+\.\d+$")

# Compile profiles share the same sketch; mic overrides via build_opt.h.
PROFILES: dict[str, dict] = {
    "full": {
        "label": "mic+loa",
        "have_speaker": 1,
        "version": None,  # use FW_VERSION from config.h
    },
    "mic": {
        "label": "chỉ mic",
        "have_speaker": 0,
        "version": "0.1.6",
    },
}
BUILD_OPT = SKETCH_DIR / "build_opt.h"  # legacy; ESP8266 3.x ignores this
GLOBALS_H = SKETCH_DIR / "KatBot.ino.globals.h"


def cli_path() -> str:
    override = getattr(settings, "arduino_cli_path", "")
    if override:
        return override
    if Path(_CLI).exists():
        return _CLI
    return "arduino-cli"


def _update_status(phase: str, message: str, ok: bool | None = None) -> None:
    _status.update({"phase": phase, "ok": ok, "message": message, "ts": int(time.time() * 1000)})


def sketch_fw_version() -> str:
    """Read FW_VERSION from firmware/KatBot/config.h (source tree)."""
    path = SKETCH_DIR / "config.h"
    try:
        text = path.read_text(encoding="utf-8")
    except OSError:
        return ""
    m = re.search(r'#\s*define\s+FW_VERSION\s+"([^"]+)"', text)
    return m.group(1) if m else ""


def _version_key(ver: str) -> tuple[int, ...]:
    try:
        return tuple(int(p) for p in ver.split("."))
    except ValueError:
        return (0, 0, 0)


def release_dir(version: str) -> Path:
    if not _VER_RE.match(version):
        raise ValueError("invalid firmware version")
    return RELEASES_DIR / version


def resolve_profile(name: str | None) -> tuple[str, dict]:
    key = (name or "full").strip().lower() or "full"
    if key not in PROFILES:
        raise ValueError(f"unknown firmware profile {name!r}")
    return key, PROFILES[key]


def profile_version(profile: dict) -> str:
    ver = (profile.get("version") or sketch_fw_version() or "").strip()
    if not _VER_RE.match(ver):
        raise ValueError(f"invalid FW_VERSION {ver!r}")
    return ver


def _write_build_opt(profile: dict) -> None:
    """ESP8266 3.x: put flags in Sketch.ino.globals.h /*@create-file:build.opt@*/ block."""
    have = int(profile["have_speaker"])
    ver = profile_version(profile)
    GLOBALS_H.write_text(
        "/* Auto-generated by backend firmware compile — do not edit by hand. */\n"
        "/*@create-file:build.opt@\n"
        f"-DKATBOT_HAVE_SPEAKER={have}\n"
        f'-DFW_VERSION=\\"{ver}\\"\n'
        "*/\n",
        encoding="utf-8",
    )
    # Remove unsupported legacy file so it cannot confuse the tree.
    try:
        BUILD_OPT.unlink(missing_ok=True)
    except OSError:
        pass


def archive_build(version: str | None = None, *, profile: str | None = None) -> dict:
    """Copy compiled bin into firmware/releases/<version>/."""
    ver = (version or sketch_fw_version() or "").strip()
    if not _VER_RE.match(ver):
        raise ValueError(f"invalid FW_VERSION {ver!r}")
    src_bin = BUILD_DIR / "KatBot.ino.bin"
    if not src_bin.is_file():
        raise FileNotFoundError("missing KatBot.ino.bin — compile first")
    dest = release_dir(ver)
    dest.mkdir(parents=True, exist_ok=True)
    dest_bin = dest / "KatBot.ino.bin"
    dest_bin.write_bytes(src_bin.read_bytes())
    meta: dict = {
        "version": ver,
        "bin": "KatBot.ino.bin",
        "size": dest_bin.stat().st_size,
        "ts": int(time.time() * 1000),
        "fqbn": FQBN,
    }
    if profile:
        meta["profile"] = profile
        meta["label"] = PROFILES.get(profile, {}).get("label", profile)
    (dest / "manifest.json").write_text(
        json.dumps(meta, ensure_ascii=False, indent=2) + "\n",
        encoding="utf-8",
    )
    return meta


def list_releases() -> list[dict]:
    """Return archived firmware builds, newest semver first."""
    if not RELEASES_DIR.is_dir():
        return []
    items: list[dict] = []
    for path in RELEASES_DIR.iterdir():
        if not path.is_dir() or not _VER_RE.match(path.name):
            continue
        bin_path = path / "KatBot.ino.bin"
        if not bin_path.is_file():
            continue
        meta: dict = {
            "version": path.name,
            "size": bin_path.stat().st_size,
            "ts": int(bin_path.stat().st_mtime * 1000),
        }
        man = path / "manifest.json"
        if man.is_file():
            try:
                data = json.loads(man.read_text(encoding="utf-8"))
                if isinstance(data, dict):
                    meta.update(
                        {
                            k: data[k]
                            for k in ("size", "ts", "fqbn", "profile", "label")
                            if k in data
                        }
                    )
                    meta["version"] = path.name
            except (OSError, json.JSONDecodeError):
                pass
        if "label" not in meta:
            if meta.get("profile") == "mic" or path.name.startswith("0.1."):
                meta["label"] = "chỉ mic"
            else:
                meta["label"] = "mic+loa"
        items.append(meta)
    items.sort(key=lambda x: _version_key(str(x["version"])), reverse=True)
    return items


def get_status() -> dict:
    out = dict(_status)
    out["fw_version"] = sketch_fw_version()
    out["profiles"] = [
        {
            "id": key,
            "label": p["label"],
            "version": p["version"] or sketch_fw_version(),
        }
        for key, p in PROFILES.items()
    ]
    releases = list_releases()
    out["releases"] = releases
    out["latest_release"] = releases[0]["version"] if releases else None
    return out


async def list_ports() -> list[dict]:
    """Return serial ports from arduino-cli board list as JSON."""
    try:
        proc = await asyncio.create_subprocess_exec(
            cli_path(), "board", "list", "--format", "json",
            stdout=asyncio.subprocess.PIPE,
            stderr=asyncio.subprocess.PIPE,
            env={**os.environ, "ARDUINO_DIRECTORIES_DATA": os.path.join(os.environ.get("LOCALAPPDATA", ""), "Arduino15")},
        )
        stdout, stderr = await asyncio.wait_for(proc.communicate(), timeout=15)
    except FileNotFoundError:
        log.warning("arduino-cli not found at %s", cli_path())
        return []
    except asyncio.TimeoutError:
        log.warning("arduino-cli board list timed out")
        return []

    if proc.returncode != 0:
        log.warning("board list error: %s", stderr.decode(errors="replace"))
        return []

    try:
        data = json.loads(stdout)
    except json.JSONDecodeError:
        return []

    # arduino-cli >= 0.35 returns {"detected_ports": [...]}
    ports = data if isinstance(data, list) else data.get("detected_ports", [])
    result = []
    for p in ports:
        addr = p.get("port", {}).get("address") or p.get("address", "")
        proto = p.get("port", {}).get("protocol", "") or p.get("protocol", "")
        label = p.get("port", {}).get("label", "") or addr
        boards = p.get("matching_boards", [])
        board_name = boards[0].get("name", "") if boards else ""
        result.append({
            "port": addr,
            "protocol": proto,
            "label": label,
            "board": board_name,
        })
    return [r for r in result if r["port"]]


async def _stream_subprocess(
    args: list[str],
    env: dict | None = None,
) -> AsyncIterator[str]:
    """Yield output lines from a subprocess, then a sentinel {"exit_code": N}."""
    proc = await asyncio.create_subprocess_exec(
        *args,
        stdout=asyncio.subprocess.PIPE,
        stderr=asyncio.subprocess.STDOUT,
        env=env or os.environ.copy(),
    )
    assert proc.stdout is not None
    while True:
        line = await proc.stdout.readline()
        if not line:
            break
        yield line.decode(errors="replace").rstrip("\n\r")
    await proc.wait()
    yield json.dumps({"exit_code": proc.returncode})


async def run_compile(profile: str | None = None) -> AsyncIterator[str]:
    """Compile firmware (full or mic) and yield log lines (SSE-ready strings)."""
    if _flash_lock.locked():
        yield "data: Đang có tác vụ khác đang chạy, vui lòng đợi.\n\n"
        return

    try:
        profile_id, profile_cfg = resolve_profile(profile)
        ver = profile_version(profile_cfg)
    except ValueError as exc:
        yield f"data: {exc}\n\n"
        yield "data: [DONE]\n\n"
        return

    async with _flash_lock:
        label = profile_cfg["label"]
        _update_status("compiling", f"Đang biên dịch {label} ({ver})…")
        BUILD_DIR.mkdir(parents=True, exist_ok=True)
        try:
            await asyncio.to_thread(_write_build_opt, profile_cfg)
        except Exception as exc:
            _update_status("error", f"Không ghi build_opt.h: {exc}", ok=False)
            yield f"data: ✗ Không ghi build_opt.h — {exc}\n\n"
            yield "data: [DONE]\n\n"
            return

        args = [
            cli_path(),
            "compile",
            "--fqbn", FQBN,
            "--warnings", "default",
            "--build-path", str(BUILD_DIR),
            "--clean",
            str(SKETCH_DIR),
        ]
        env = {
            **os.environ,
            "ARDUINO_DIRECTORIES_DATA": os.path.join(os.environ.get("LOCALAPPDATA", ""), "Arduino15"),
            "ARDUINO_DIRECTORIES_USER": os.path.join(os.environ.get("USERPROFILE", ""), "Documents", "Arduino"),
        }
        log.info("compile %s %s: %s", profile_id, ver, shlex.join(args))
        yield f"data: Bắt đầu biên dịch firmware {ver} ({label})…\n\n"
        exit_code = 0
        async for line in _stream_subprocess(args, env):
            try:
                obj = json.loads(line)
                exit_code = obj.get("exit_code", 0)
                if exit_code == 0:
                    try:
                        meta = await asyncio.to_thread(
                            archive_build, ver, profile=profile_id
                        )
                        _update_status(
                            "idle",
                            f"Biên dịch thành công — lưu bản {meta['version']} ({label}).",
                            ok=True,
                        )
                        yield (
                            f"data: ✓ Biên dịch thành công. Đã lưu bản {meta['version']} "
                            f"({label}, {meta['size']} byte).\n\n"
                        )
                    except Exception as exc:
                        log.exception("archive failed")
                        _update_status("idle", "Biên dịch thành công (chưa lưu release).", ok=True)
                        yield f"data: ✓ Biên dịch thành công.\n\n"
                        yield f"data: Cảnh báo: chưa lưu release — {exc}\n\n"
                else:
                    _update_status("error", f"Lỗi biên dịch (exit {exit_code}).", ok=False)
                    yield f"data: ✗ Biên dịch lỗi (exit code {exit_code}).\n\n"
                yield "data: [DONE]\n\n"
            except json.JSONDecodeError:
                # Filter noisy progress lines but keep errors
                clean = line.strip()
                if clean:
                    yield f"data: {clean}\n\n"


async def run_flash(port: str, version: str | None = None) -> AsyncIterator[str]:
    """Flash a released (or latest) firmware build to `port`."""
    releases = list_releases()
    ver = (version or "").strip()
    if not ver:
        ver = sketch_fw_version() if any(r["version"] == sketch_fw_version() for r in releases) else ""
        if not ver and releases:
            ver = str(releases[0]["version"])
    if not ver or not _VER_RE.match(ver):
        yield "data: Chưa chọn phiên bản firmware hợp lệ. Biên dịch trước hoặc chọn bản trong danh sách.\n\n"
        yield "data: [DONE]\n\n"
        return
    input_dir = release_dir(ver)
    bin_path = input_dir / "KatBot.ino.bin"
    if not bin_path.is_file():
        yield f"data: Không tìm thấy bản {ver}. Hãy biên dịch khi FW_VERSION={ver}.\n\n"
        yield "data: [DONE]\n\n"
        return

    if _flash_lock.locked():
        yield "data: Đang có tác vụ khác đang chạy, vui lòng đợi.\n\n"
        return

    async with _flash_lock:
        _update_status("flashing", f"Đang nạp {ver} lên {port}…")
        args = [
            cli_path(),
            "upload",
            "--fqbn", f"{FQBN}:baud=115200",
            "--port", port,
            "--input-dir", str(input_dir),
            str(SKETCH_DIR),
        ]
        env = {
            **os.environ,
            "ARDUINO_DIRECTORIES_DATA": os.path.join(os.environ.get("LOCALAPPDATA", ""), "Arduino15"),
            "ARDUINO_DIRECTORIES_USER": os.path.join(os.environ.get("USERPROFILE", ""), "Documents", "Arduino"),
        }
        log.info("flash %s to %s: %s", ver, port, shlex.join(args))
        yield f"data: Bắt đầu nạp firmware {ver} lên {port}…\n\n"
        async for line in _stream_subprocess(args, env):
            try:
                obj = json.loads(line)
                exit_code = obj.get("exit_code", 0)
                if exit_code == 0:
                    _update_status("idle", f"Nạp {ver} thành công lên {port}.", ok=True)
                    yield f"data: ✓ Nạp firmware {ver} thành công lên {port}.\n\n"
                else:
                    _update_status("error", f"Lỗi nạp {ver} (exit {exit_code}).", ok=False)
                    yield f"data: ✗ Nạp lỗi (exit code {exit_code}).\n\n"
                    yield (
                        "data: Gợi ý: esptool không vào được bootloader. "
                        "Rút DIN amp khỏi RX (GPIO3) lúc nạp; GPIO15/D8 phải LOW, GPIO2/D4 phải HIGH. "
                        "Giữ FLASH trên NodeMCU, bấm RST, thả RST, rồi thả FLASH khi thấy Connecting…. "
                        "Đóng Serial Monitor / Arduino IDE. Thử cáp USB khác, baud 115200.\n\n"
                    )
                yield "data: [DONE]\n\n"
            except json.JSONDecodeError:
                clean = line.strip()
                if clean:
                    yield f"data: {clean}\n\n"
